import test from "node:test";
import assert from "node:assert/strict";
import {
  LLMS_TEXT,
  OPENAPI_DOCUMENT,
  OWNERSHIP_PROOF,
  X402_DISCOVERY_DOCUMENT,
} from "../lib/discovery";
import {
  BOUNTY_RESOURCE_URL,
  EXAMPLE_INPUT,
  EXAMPLE_OUTPUT,
  PUBLIC_BASE_URL,
} from "../lib/product";
import { scoreBounty } from "../lib/scoring";

const paidOperation = OPENAPI_DOCUMENT.paths["/api/bounty-score"].post;

test("OpenAPI advertises the paid route in x402scan-compatible form", () => {
  assert.equal(OPENAPI_DOCUMENT.openapi, "3.1.0");
  assert.ok(OPENAPI_DOCUMENT.info["x-guidance"]);
  assert.equal(paidOperation.operationId, "scoreBounty");
  assert.equal(paidOperation["x-payment-info"].price.amount, "0.01");
  assert.deepEqual(paidOperation["x-payment-info"].protocols[0], {
    x402: {
      version: 2,
      scheme: "exact",
      network: "eip155:8453",
      asset: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      payTo: "0xc7A7563793C3aeaCA9177a4aa2e4fd7C01F7Eb35",
      facilitator: "https://facilitator.payai.network",
    },
  });
  assert.ok("402" in paidOperation.responses);
  assert.deepEqual(paidOperation.security, []);
});

test("compatibility discovery fans out to the canonical paid resource", () => {
  assert.equal(X402_DISCOVERY_DOCUMENT.version, 1);
  assert.deepEqual(X402_DISCOVERY_DOCUMENT.resources, [BOUNTY_RESOURCE_URL]);
  assert.deepEqual(X402_DISCOVERY_DOCUMENT.ownershipProofs, [OWNERSHIP_PROOF]);
});

test("ownership proof has a complete EVM signature shape", () => {
  assert.match(OWNERSHIP_PROOF, /^0x[0-9a-f]{130}$/i);
  assert.deepEqual(OPENAPI_DOCUMENT["x-discovery"].ownershipProofs, [OWNERSHIP_PROOF]);
});

test("free fixed example is generated by the real scoring core", () => {
  assert.deepEqual(EXAMPLE_OUTPUT, scoreBounty(EXAMPLE_INPUT));
  assert.ok(EXAMPLE_OUTPUT.result.score > 0);
  assert.notEqual(EXAMPLE_OUTPUT.result.verdict, "skip");
});

test("llms.txt points agents to canonical discovery and paid routes", () => {
  assert.match(LLMS_TEXT, new RegExp(`${PUBLIC_BASE_URL.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/openapi\\.json`));
  assert.match(LLMS_TEXT, /POST https:\/\/compounder-market-api\.vercel\.app\/api\/bounty-score/);
  assert.match(LLMS_TEXT, /\$0\.01 USDC/);
  assert.match(LLMS_TEXT, /no API key or account/i);
});
