import { EXAMPLE_INPUT, EXAMPLE_OUTPUT, PUBLIC_BASE_URL } from "@/lib/product";

const inputExample = JSON.stringify(EXAMPLE_INPUT, null, 2);
const outputExample = JSON.stringify(
  {
    score: EXAMPLE_OUTPUT.result.score,
    verdict: EXAMPLE_OUTPUT.result.verdict,
    expectedValueUsd: EXAMPLE_OUTPUT.result.expectedValueUsd,
    strengths: EXAMPLE_OUTPUT.result.strengths,
    risks: EXAMPLE_OUTPUT.result.risks,
    recommendedAction: EXAMPLE_OUTPUT.result.recommendedAction,
  },
  null,
  2,
);

const structuredData = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Compounder Market API",
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Web",
  url: PUBLIC_BASE_URL,
  description: "Machine-payable decision tools for autonomous operators on Base.",
  offers: {
    "@type": "Offer",
    price: "0.01",
    priceCurrency: "USD",
    description: "One Bounty Fit Scorer assessment, settled in USDC on Base",
  },
};

export default function Home() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      <main>
        <nav>
          <span className="brand">COMPOUNDER</span>
          <div className="nav-links">
            <a href="/openapi.json">OpenAPI</a>
            <a href="/llms.txt">llms.txt</a>
            <a href="/api/health">Health</a>
            <a
              href="https://github.com/SupremeDreamZ/compounder-market-api"
              rel="noreferrer"
              target="_blank"
            >
              Source
            </a>
          </div>
        </nav>

        <section className="hero">
          <p className="eyebrow">MACHINE-PAYABLE DECISION INTELLIGENCE</p>
          <h1>Spend one cent.<br />Avoid the wrong bounty.</h1>
          <p className="lede">
            The Bounty Fit Scorer evaluates paid opportunities by payment certainty, operator fit,
            AI leverage, reuse value, time-to-cash, payout quality, execution friction, and competition.
          </p>
          <div className="badges">
            <span>$0.01 USDC</span>
            <span>Base Mainnet</span>
            <span>x402 v2</span>
            <span>OpenAPI 3.1</span>
            <span>Wallet-verified origin</span>
          </div>
        </section>

        <section className="grid">
          <article>
            <p className="label">PAID ENDPOINT</p>
            <h2>POST /api/bounty-score</h2>
            <p>
              Returns a 0–100 score, pursue/skip verdict, expected value, dimension breakdown,
              hard stops, risks, strengths, and a next action.
            </p>
          </article>
          <article>
            <p className="label">PAYMENT</p>
            <h2>Exact USDC settlement</h2>
            <p>
              Payments settle directly to the operator wallet on Base through an accountless
              production facilitator. No API key or subscription is required.
            </p>
          </article>
          <article>
            <p className="label">DOCTRINE</p>
            <h2>Certainty over headline value</h2>
            <p>
              Short, verifiable, AI-leveraged work that creates reusable assets outranks crowded,
              speculative, capital-intensive opportunities.
            </p>
          </article>
        </section>

        <section className="docs">
          <div>
            <p className="label">FREE DISCOVERY</p>
            <h2>Inspect the contract before paying.</h2>
            <p>
              OpenAPI, llms.txt, x402 compatibility metadata, and endpoint documentation are all
              public. POST invokes payment negotiation and settles only after a successful assessment.
            </p>
            <div className="link-row">
              <a className="button" href="/openapi.json">OpenAPI schema</a>
              <a className="button secondary" href="/api/bounty-score">Endpoint docs</a>
            </div>
          </div>
          <pre><code>{inputExample}</code></pre>
        </section>

        <section className="docs">
          <pre><code>{outputExample}</code></pre>
          <div>
            <p className="label">FREE FIXED SAMPLE</p>
            <h2>See the real scorer output.</h2>
            <p>
              The sample is generated by the same deterministic core as paid calls, so buyers can
              validate structure and usefulness before opening a wallet.
            </p>
            <a className="button" href="/api/bounty-score/example">Open free sample JSON</a>
          </div>
        </section>

        <footer>
          <span>Compounder Market API · v0.1.0</span>
          <span>Built to turn reusable intelligence into Base-denominated revenue.</span>
        </footer>
      </main>
    </>
  );
}
